### ISSUE TITLE
ImportError: cannot import name 'Undefined' from 'pydantic.fields'

### ISSUE THREAD

**Issue by Romanio1997** [philz1337x/clarity-upscaler#50]
Does not install locally normally errors appear and the install process aborts.

Creating venv in directory C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv using python "C:\Program Files\Python310\python.exe"
venv "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\Scripts\Python.exe"
xformers_package xformers==0.0.22
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: <none>
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.1
Installing requirements
Installing sd-webui-controlnet requirement: fvcore
Installing sd-webui-controlnet requirement: mediapipe
Installing sd-webui-controlnet requirement: onnxruntime
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-webui-controlnet requirement: svglib
Installing sd-webui-controlnet requirement: insightface
Installing sd-webui-controlnet requirement: handrefinerportable
Installing sd-webui-controlnet requirement: depth_anything
Launching Web UI with arguments:

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\launch.py", line 48, in <module>
    main()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\launch.py", line 44, in main
    start()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\modules\launch_utils.py", line 476, in start
    import webui
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\modules\initialize.py", line 16, in imports
    import pytorch_lightning  # noqa: F401
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\torchmetrics\__init__.py", line 30, in <module>
    from torchmetrics import functional  # noqa: E402
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 122, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 17, in <module>
    from torchmetrics.functional.text.chrf import chrf_score
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\torchmetrics\functional\text\chrf.py", line 32, in <module>
    _EPS_SMOOTHING = tensor(1e-16)
C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\torchmetrics\functional\text\chrf.py:32: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  _EPS_SMOOTHING = tensor(1e-16)
Traceback (most recent call last):
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\launch.py", line 48, in <module>
    main()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\launch.py", line 44, in main
    start()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\modules\launch_utils.py", line 476, in start
    import webui
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>    from .applications import FastAPI as FastAPI
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>    from fastapi import params
  File "C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (C:\pinokio\ComfyUI_windows_portable\clarity-upscaler\venv\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .

**Comment by philz1337x** [comment]
Are you trying to run this repo in ComfyUI? 
This is not possible, for ComfyUI please use the workflow in this repo: https://github.com/philz1337x/ComfyUI-ClarityAI
